spring:
  application:
    name: DoranDoran
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-dawn-morning-a101t8cb-pooler.ap-southeast-1.aws.neon.tech:5432/dorandoran?sslmode=require
    username: dorandoran_owner
    password: npg_KaquC0eUzBj8
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      leak-detection-threshold: 10000
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        userServerPrepStmts: true
  mvc: 
    view:
      suffix: .html
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mustache:
    prefix: classpath:/templates/
    suffix: .mustache
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m

server:
  port: 9090

mybatis:
  type-aliases-package: kr.ac.kopo.dorandoran.model
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

kakao:
  api:
    key: 4bc2d5571cca59b1567f1545be890edc

cloudflare:
  r2:
    endpoint: ${R2_END_POINT}
    bucket-name: ${R2_BUCKET_NAME}
    access-key: ${R2_ACCESS_KEY}
    secret-key: ${R2_SECRET_KEY}	
